name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v5

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/backend-eval2:latest" .

      - name: Subir imagen a Docker Hub
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/backend-eval2:latest"

      - name: Desplegar en EC2 privada vía Bastion
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > key.pem << 'EOF'
            ${{ secrets.EC2_SSH_KEY }}
            EOF

            chmod 600 key.pem

            ssh -o StrictHostKeyChecking=no \
              -i key.pem \
              ${{ secrets.EC2_USER }}@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
                docker stop backend-eval2 || true
                docker rm backend-eval2 || true
                docker pull "${{ secrets.DOCKERHUB_USERNAME }}/backend-eval2:latest"

                docker run -d \
                  --name backend-eval2 \
                  -p 5000:5000 \
                  "${{ secrets.DOCKERHUB_USERNAME }}/backend-eval2:latest"
            EOF

            rm -f key.pem